import io
import zipfile
import pytest
from test_api import arena, PREFIX, payload
from app.models import Contest
from app.services.external_problems import canonical_url, parse_statement
from app.services.problem_documents import validate_document
from app.services.code_review import comment_review

CF = '<div class="problem-statement"><div class="title">A. Local sum</div><p>Sum the integers.</p><div class="sample-test"><div class="input"><pre>1 2<br/>3 4</pre></div><div class="output"><pre>3<br/>7</pre></div></div></div>'


def test_external_adapters_and_untrusted_urls(arena):
    clients, _, _ = arena
    url = "https://codeforces.com/problemset/problem/4/A"
    parsed = parse_statement(url, CF)
    assert parsed["tests"][0]["input_data"] == "1 2\n3 4\n"
    assert parsed["review_required"] and "Source: https://" in parsed["description"]
    for bad in [
        "http://codeforces.com/problemset/problem/4/A",
        "https://localhost/a",
        "https://codeforces.com@127.0.0.1/a",
        "https://codeforces.com:444/problemset/problem/4/A",
        "https://codeforces.com/api/problemset.problems",
    ]:
        with pytest.raises(ValueError):
            canonical_url(bad)
    assert (
        clients["student"]
        .post(PREFIX + "/problems/import-url", json={"url": url, "html": CF})
        .status_code
        == 403
    )
    result = clients["teacher"].post(
        PREFIX + "/problems/import-url", json={"url": url, "html": CF}
    )
    assert result.status_code == 200, result.text
    html = '<span class="h2">A - Local sum</span><div id="task-statement"><span class="lang-en"><section><h3>Sample Input 1</h3><pre>1 2</pre></section><section><h3>Sample Output 1</h3><pre>3</pre></section></span></div>'
    assert (
        parse_statement("https://atcoder.jp/contests/abc001/tasks/abc001_1", html)[
            "tests"
        ][0]["expected"]
        == "3\n"
    )
    assert (
        parse_statement(
            "https://cses.fi/problemset/task/1/",
            '<h1>Local sum</h1><div class="content"><pre>1 2</pre><pre>3</pre></div>',
        )["tests"][0]["expected"]
        == "3\n"
    )


def test_documents_follow_contest_permissions_and_locks(arena):
    clients, factory, ids = arena
    base = f"{PREFIX}/problems/{ids['problem']}/documents"
    pdf = b"%PDF-1.4\nminimal test\n%%EOF\n"
    assert (
        clients["student"]
        .post(base, files={"file": ("statement.pdf", pdf)})
        .status_code
        == 403
    )
    assert (
        clients["teacher"]
        .post(base, files={"file": ("statement.pdf", pdf)})
        .status_code
        == 409
    )
    with factory() as db:
        db.get(Contest, ids["contest"]).status = "DRAFT"
        db.commit()
    assert (
        clients["outsider"]
        .post(base, files={"file": ("statement.pdf", pdf)})
        .status_code
        == 404
    )
    result = clients["teacher"].post(base, files={"file": ("statement.pdf", pdf)})
    assert result.status_code == 201, result.text
    path = base + "/" + str(result.json()["id"])
    assert clients["teacher"].get(path).content == pdf
    assert clients["student"].get(
        path + f"?contest_id={ids['contest']}"
    ).status_code in (403, 404)
    with factory() as db:
        db.get(Contest, ids["contest"]).status = "RUNNING"
        db.commit()
    downloaded = clients["student"].get(path + f"?contest_id={ids['contest']}")
    assert (
        downloaded.content == pdf
        and "attachment;" in downloaded.headers["content-disposition"]
    )
    assert clients["student"].get(path).status_code == 404
    assert clients["teacher"].delete(path).status_code == 409
    with factory() as db:
        db.get(Contest, ids["contest"]).status = "FINISHED"
        db.commit()
    assert clients["teacher"].delete(path).status_code == 204
    assert clients["teacher"].get(path).status_code == 404


def test_docx_validation_and_comment_review():
    def docx(extra=None):
        buf = io.BytesIO()
        with zipfile.ZipFile(buf, "w") as z:
            z.writestr("[Content_Types].xml", "<Types/>")
            z.writestr("word/document.xml", "<document/>")
            if extra:
                z.writestr(extra, "bad")
        return buf.getvalue()

    assert validate_document("statement.docx", docx())[1].endswith("document")
    for name in ["word/vbaProject.bin", "word/embeddings/object.bin", "../escape"]:
        with pytest.raises(ValueError):
            validate_document("x.docx", docx(name))
    with pytest.raises(ValueError):
        validate_document("x.pdf", b"<html>")
    assert not comment_review('x="generated by ChatGPT"', "python3")["findings"]
    review = comment_review("# generated by ChatGPT\nprint(3)", "python3")
    assert review["findings"][0]["line"] == 1 and not review["authorship_determined"]
    assert not comment_review('const x="generated by ChatGPT";', "javascript")[
        "findings"
    ]
    assert comment_review("/* generated by ChatGPT */", "cpp20")["findings"]


def test_comment_review_is_teacher_only(arena):
    clients, _, ids = arena
    body = payload(ids)
    body["source"] = "# generated by ChatGPT\nprint(3)"
    sid = clients["student"].post(PREFIX + "/submissions", json=body).json()["id"]
    path = PREFIX + f"/submissions/{sid}"
    assert "code_review" not in clients["student"].get(path).json()
    assert clients["teacher"].get(path).json()["code_review"]["findings"]
    assert clients["student"].get(PREFIX + "/network/windows-script").status_code == 403
    assert clients["teacher"].get(PREFIX + "/network/windows-script").status_code == 200


def test_language_settings_and_import_private_address_rejection(arena, monkeypatch):
    from app.services.external_problems import fetch_statement
    clients, factory, ids = arena
    path = f"{PREFIX}/contests/{ids['contest']}/languages"
    assert clients['teacher'].patch(path,json={'languages':['go']}).status_code == 409
    with factory() as db:
        db.get(Contest,ids['contest']).status='FINISHED'
        db.commit()
    assert clients['student'].patch(path,json={'languages':['go']}).status_code == 403
    assert clients['teacher'].patch(path,json={'languages':[]}).status_code == 422
    response=clients['teacher'].patch(path,json={'languages':['javascript','go','csharp']})
    assert response.status_code==200 and response.json()['languages']==['javascript','go','csharp']
    monkeypatch.setattr('app.services.external_problems.socket.getaddrinfo',lambda *a,**k:[(2,1,6,'',('127.0.0.1',443))])
    with pytest.raises(ValueError,match='non-public'):
        fetch_statement('https://codeforces.com/problemset/problem/4/A')
