from enum import StrEnum


class Verdict(StrEnum):
    ACCEPTED = 'ACCEPTED'
    PARTIAL = 'PARTIAL'
    WRONG_ANSWER = 'WRONG_ANSWER'
    TIME_LIMIT_EXCEEDED = 'TIME_LIMIT_EXCEEDED'
    MEMORY_LIMIT_EXCEEDED = 'MEMORY_LIMIT_EXCEEDED'
    RUNTIME_ERROR = 'RUNTIME_ERROR'
    COMPILATION_ERROR = 'COMPILATION_ERROR'
    SYSTEM_ERROR = 'SYSTEM_ERROR'
    OUTPUT_LIMIT_EXCEEDED = 'OUTPUT_LIMIT_EXCEEDED'
